# Generated by Django 4.0.5 on 2022-07-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['-creado'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
