# Generated by Django 4.0.5 on 2022-07-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicios_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
    ]
